version: '3'

services:
  mongo: 
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/datadir:/data/db
      - ./db/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbadmin
      MONGO_INITDB_ROOT_PASSWORD: 1234
  mongo-express:
    image: mongo-express:0.54
    container_name: mogo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'